import { createSlice } from '@reduxjs/toolkit';

export const mailSlice = createSlice({
  name: 'mail',
  initialState: {
    sendMessageIsOpen: false, 
  reducers: {
    openSendMessage:state =>{
      state.sendMessageIsOpen =true
    },
    closeSendMessage:state => {
      state.sendMessageIsOpen = false;
    },
    
    },
  },
});

// Exporting the actions generated by createSlice
export const { openSendMessage, closeSendMessage, incrementByAmount } = mailSlice.actions;

// Selector function to get the value from the state
export const selectSendMessageIsOpen = (state) => state.mail.value;

// Thunk function to increment the value only if the current value is odd
// export const incrementIfOdd = (amount) => (dispatch, getState) => {
//   const currentValue = selectCount(getState());
//   if (currentValue % 2 === 1) {
//     dispatch(incrementByAmount(amount));
//   }
// };

// Exporting the reducer function to be used in the store
export default mailSlice.reducer;
